
--카테고리 테이블
-- 생성
CREATE TABLE IF NOT EXISTS "CATEGORY"
(
	"CATEGORY_ID" BIGSERIAL NOT NULL,
	"CATEGORY_" VARCHAR(100) NOT NULL,
	"DESCRIPTION" VARCHAR(500),
	PRIMARY KEY("CATEGORY_ID")
)

-- 삭제
DROP TABLE "CATEGORY";

-- 코멘트 추가
COMMENT ON COLUMN "CATEGORY"."CATEGORY_ID" IS '카테고리 번호';
COMMENT ON COLUMN "CATEGORY"."CATEGORY_NAME" IS '카테고리 이름';
COMMENT ON COLUMN "CATEGORY"."DESCRIPTION" IS '카테고리 설명';

-- 삽입
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('마케팅','광고 데이터 및 트랜드 데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('금융&경제','주택 데이터 및 주가데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('환경&에너지','미세먼지데이터, 기상데이터, iris데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('범죄','사기데이터, 사건데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('문화 ','영화, 게임, 스포츠 데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('정보통신','ADFA-LD데이터, 로그데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('건강','질병데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('제조','제조설비 이상감지 데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('정치','국회의원 언급량 등 데이터');
INSERT INTO public."CATEGORY"("CATEGORY_NAME","DESCRIPTION") VALUES ('기타','카테고리에 정의되지 않은 기타 데이터');												

-- 도메인 테이블 생성
create table if not exists "DOMAIN"
(
  "DOMAIN_ID" BIGSERIAL not null,
   "CATEGORY_ID" BIGINT not null,
   "TITLE" VARCHAR(100) not null,
   "MODEL_SEQUENCE_PK" BIGINT REFERENCES "MODEL"("MODEL_SEQUENCE_PK"),
   "PROJECT_SEQUENCE_PK" BIGINT REFERENCES "PROJECT"("PROJECT_SEQUENCE_PK"),
   "REGT_DATE" TIMESTAMP NOT NULL,
   "REGT_USER" VARCHAR(50) NOT NULL,  
   "DESCRIPTION" VARCHAR(500) NOT NULL,
   PRIMARY KEY("DOMAIN_ID")
);

-- 딥러닝 테이블 생성
create table "DEEPLEARNING"
(
   "ID" BIGSERIAL,
   "NAME" VARCHAR(500) not null,
   "DESCRIPTION" VARCHAR(4000),
   "USER_ID" VARCHAR(50),
   "REGT_DATE" TIMESTAMP NOT NULL,
   PRIMARY KEY("ID")
);

--INSERT into "DEEPLEARNING" VALUES(nextval('"DEEPLEARNING_ID_seq"'),'test1','test2','test3',now());